### ISSUE TITLE
$main_conf is not an absolute path by default on RedHat 6

### ISSUE THREAD

**Issue by XMol** [CERIT-SC/puppet-tuned#3]
Hello,

in init.pp on [line 22](https://github.com/CERIT-SC/puppet-tuned/blob/master/manifests/init.pp#L22), a check is made to ensure that the `$main_conf` parameter contains an absolute path. However, by default for some operating systems, an empty string is used by means of params.pp ([line 27](https://github.com/CERIT-SC/puppet-tuned/blob/master/manifests/params.pp#L27)).

The check is sensible and should be done, but only when the parameter actually contains something else besides an empty string (or nil?). The current code actually should work thanks to the automatic conversion to boolean data type, but for us, it doesn't.

```
[root@somenode ~]# cat /etc/redhat-release
Scientific Linux release 6.8 (Carbon)

[root@somenode ~]# puppet --version
3.8.4

[root@somenode ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Notice: /File[/var/lib/puppet/lib/facter/tuned.rb]/ensure: defined content as '{md5}ac5773334a2644c799e9bf7ac51204f7'
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, "" is not an absolute path. at /etc/puppet/modules/tuned/manifests/init.pp:22:5 on node somenode
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

I don't understand where this error comes from. Writing minimalistic Puppet modules work just fine with this kind of automatic data type conversion in our setup (possibly this is an issue triggered by Hiera?).

In order to work around the problem, I tried to assign either `/` or `false`, both resulted in an error ("Invalid resource type ini_setting" and "empty(): Requires either array, hash, string or integer to work with" respectively).

Could you please update the code and not rely on automatic conversion anymore? In tuned::config ([line 22](https://github.com/CERIT-SC/puppet-tuned/blob/master/manifests/config.pp#L22)) you check whether `$main_conf` is not empty. Streamlining the checks, i.e. either check in one module only or check in the same way, would help in this situation.

Thank you,
Xavier.

**Comment by vholer** [comment]
Fixed by your PR #5, thank you!
