### ISSUE TITLE
Unresolved resource type 'ini_setting'

### ISSUE THREAD

**Issue by XMol** [CERIT-SC/puppet-tuned#4]
Hello,

the README doesn't state any other dependencies apart from puppetlabs' [stdlib](https://github.com/puppetlabs/puppetlabs-stdlib). But the `ini_setting` resource type is not defined by that module or tuned itself, thus I came across an "invalid resource type" error.

I assume, one has to include an additional module defining `ini_setting`, e.g. [puppetlabs-inifile](https://github.com/puppetlabs/puppetlabs-inifile)?

Best regards,
Xavier.

**Comment by vholer** [comment]
Fixed by your PR #5, thank you.
